version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./:/app
    command: streamlit run combined_app.py --server.port=8501 --server.address=0.0.0.0
